[book]
authors = ["Krsna"]
language = "en"
multilingual = false
src = "src"
title = "Bhagavad-gita (1972)"
[output.html]
default-theme = "rust"
additional-css = ["custom.css"]
[output.html.search]
enable = true
limit-results = 650 
teaser-word-count = 0
